[tool.poetry]
name = "test-poetry2nix-flake"
version = "0.1.0"
description = ""
authors = ["Dmytro Kyrychuk <dmytro@kyrych.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
